# Offers
## Get list of offers
GET http://localhost:3022/offers HTTP/1.1
Content-Type: application/json

###

GET http://localhost:5000/offers/1810c5889ba0a043907301j HTTP/1.1
Content-Type: application/json

###
